POST localhost:8083/aois
Content-Type: application/json

{
  "name": "북한산",
  "area": [
    {"x": 127.02, "y": 37.742},
    {"x": 127.023, "y": 37.664},
    {"x": 126.945, "y": 37.605},
    {"x": 126.962, "y": 37.692},
    {"x": 127.02, "y": 37.742}
  ]
}